In [ ]:
DATA_DIR = r"C:\Users\Mehran\Desktop\Azizpour\Datasets\Gnome"
image_data_dir = DATA_DIR + '\\by-id\\'
image_dir = DATA_DIR + "\\images\\"

In [ ]:
import matplotlib.pyplot as plt
import torch
from ImageDataLoader import ImageRegionData
from torchvision import transforms, models
import torch.nn as nn
from torch.utils.data.dataloader import DataLoader
import math
import os

In [ ]:
transform = transforms.Compose([
        transforms.Resize(299),
        transforms.CenterCrop(299),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ])
batch_size = 10
image_data = ImageRegionData(DATA_DIR + "\\Regions\\country\\124\\", transform)

In [ ]:
import numpy as np
from sklearn.preprocessing import normalize

x = np.array([1,2,3,4,5,6,7,7,8])
x[:len(x) - 7:-1]
# norm1 = x / np.linalg.norm(x)
# norm2 = normalize(x[:,np.newaxis], axis=0).ravel()
# print(np.all(norm1 == norm2))
# print(norm1)

In [ ]:
os.listdir(DATA_DIR + "\\Regions\\country\\124\\new")

In [ ]:
image_data.imgs

In [ ]:
image_data[0][0].shape

In [ ]:
import os
graph_directory = DATA_DIR + '\\Regions\\' + 'urban' + '\\55'
list_nodes = os.listdir(graph_directory)
    

In [ ]:
list_nodes

In [ ]:
categories = ['country', 'urban', 'indoor', 'outdoor']
import shutil

for c in categories:
    path = DATA_DIR + '\\Regions\\' + c + '\\'
    list_fold = os.listdir(path)
    for folder in list_fold:
        file_paths = path + folder + '\\'
        list_files = os.listdir( file_paths + 'new')
        if len(list_files) == 0:
            print(folder)
#         print(folder)
#         list_files.remove('new')
#         print(list_files)
#         print(file_paths + '0')
#         print(folder)
#         os.mkdir(file_paths + 'new')
#         for f in list_files:
#             shutil.move(file_paths + f, file_paths + 'new')
    
    

In [ ]:
DATA_DIR = r"C:\Users\Mehran\Desktop\Azizpour\Datasets\Gnome"
TARGET_DIR = DATA_DIR + '\\Edges\\'

In [ ]:
import dgl
g = dgl.DGLGraph()
g.add_nodes(14)
# import pandas
# edge = pandas.read_csv(TARGET_DIR + '107926.txt').values
# g.add_edges(edge[:, 0], edge[:, 1])

In [ ]:
import torch
g.ndata['h'] = torch.ones([14,5])

In [ ]:
import networkx as nx
import matplotlib.pyplot as plt
nx.draw(g.to_networkx(), with_labels=True)
plt.show()

In [ ]:
inp = torch.rand([10, 2048])
w = torch.rand([128, 2048])
b = torch.rand(128)

In [ ]:
from TrainGraphModel import train_model

In [ ]:
model = train_model()



In [ ]:
from GraphDataset import GraphDataset
import LRP
import torch

i=5

samples = GraphDataset('countryVSurban')
model(samples[i][0])
print(samples.ids[i])

r = LRP.lrp(model)
_, index = torch.sort(torch.sum(r, dim=1))
print(index)

In [ ]:
import torch
torch.arange(4)

In [ ]:
from GraphDataset import GraphDataset
samples = GraphDataset('countryVSurban')


In [ ]:
import numpy as np
a = np.ones([5,5])

In [ ]:
a[0:6, 0:2]

In [ ]:
from CreateGraphEdge import preprocess_object_names
from visual_genome import local as vg
import os
data_dir = r"C:\Users\Mehran\Desktop\Azizpour\Datasets\Gnome"
image_id = 107926

In [ ]:
graph = vg.get_scene_graph(107926, images=data_dir+'\\', image_data_dir=data_dir + '\\by-id\\', synset_file=data_dir+'\\synsets.json') 

In [ ]:
graph.objects

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Circle


man = graph.objects[0]
cow = graph.objects[2]

# Get an example image
import matplotlib.cbook as cbook
image_file = cbook.get_sample_data(data_dir + f'\\images\\{image_id}.jpg')
img = plt.imread(image_file)

# Make some example data
# x = np.random.rand(5)*img.shape[1]
# y = np.random.rand(5)*img.shape[0]
x = [man.x + man.width / 2, cow.x + cow.width/2]
y = [man.y + man.height / 2, cow.y + cow.height / 2]

# Create a figure. Equal aspect so circles look circular
fig,ax = plt.subplots(1)
ax.set_aspect('equal')

# Show the image
ax.imshow(img)

# Now, loop through coord arrays, and create a circle at each x,y pair
for xx,yy in zip(x,y):
    circ = Circle((xx,yy),50)
    ax.add_patch(circ)
    ax.text(xx, yy, 'hello', bbox=dict(facecolor='white', alpha=0.5))

plt.plot(x[0:2], y[0:2], 'g', linewidth=5)
plt.text(abs(x[0] + x[1])/2, abs(y[0] + y[1])/2, 'is on', bbox=dict(facecolor='white', alpha=0.5))
# Show the image
plt.show()

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import networkx as nx

img=mpimg.imread(r'C:\Users\Mehran\Desktop\Azizpour\Datasets\Gnome\Regions\country\124\new\apples.jpg')
G=nx.Graph()
G.add_node(0,image= img)
G.add_node(1,image= img)
G.add_node(2,image= img)
G.add_node(3,image= img)
G.add_node(4,image= img)
G.add_node(5,image= img)

print(G.nodes())
G.add_edge(0,1)
G.add_edge(0,2)
G.add_edge(0,3)
G.add_edge(0,4)
G.add_edge(0,5)
print(G.edges())
pos=nx.circular_layout(G)

fig=plt.figure(figsize=(5,5))
ax=plt.subplot(111)
ax.set_aspect('equal')
nx.draw_networkx_edges(G,pos,ax=ax)

plt.xlim(-1.5,1.5)
plt.ylim(-1.5,1.5)

trans=ax.transData.transform
trans2=fig.transFigure.inverted().transform

piesize=0.2 # this is the image size
p2=piesize/2.0
for n in G:
    xx,yy=trans(pos[n]) # figure coordinates
    xa,ya=trans2((xx,yy)) # axes coordinates
    a = plt.axes([xa-p2,ya-p2, piesize, piesize])
    a.set_aspect('equal')
    a.imshow(G.node[n]['image'])
    a.axis('off')
ax.axis('off')
plt.show()

In [ ]:
data_dir = r"C:\Users\Mehran\Desktop\Azizpour\Datasets\Gnome\\"
graph = vg.get_scene_graph(10, images=data_dir, image_data_dir=data_dir + 'by-id\\', synset_file=data_dir+'synsets.json')


In [ ]:
for i in graph.objects:
    print(i.synsets)
#     print('forward' in i.synset.__str__())
# graph.objects

In [ ]:
from Federico.torchgraphs.src import torchgraphs as tg

In [ ]:
g = tg.Graph(
    node_features=torch.rand(5, 10),
    senders=torch.tensor([0,1,2,3]),
    receivers=torch.tensor([2,3,4,0])
)

In [ ]:
import networkx as nx
import torch

In [ ]:
torch.mean(g.node_features, dim=0).shape

In [ ]:
g.node_features

In [1]:
from Graph.VisualGenomeGraphModel import VisualGenomeGN
from Graph.Visual import VisualGenomeGNRelevance

net = VisualGenomeGN()
net.load_state_dict(torch.load(r'..\trained_graph', map_location='cuda:0'))
net_lrp = VisualGenomeGNRelevance('avg', True)
net_lrp.load_state_dict(torch.load(r'..\trained_graph', map_location='cuda:0'))



ModuleNotFoundError: No module named 'VisualGenomeGraphModel'

In [1]:
k = {}
k['helo'] = 23
k['how'] = 24
for i in k:
    print(i)

helo
how


In [7]:
import numpy as np
a = np.ones([3, 3])

In [10]:
np.where(a == 0)[0].shape[0]

0

In [13]:
class Cu:
    def __int__(self, kernel, inputs):
        # self.unique_weights, repeated = conv_factorization(kernel)
        # for r in repeated:
        #     print('hello')
        #     print(r)
        self.kernel = kernel

In [18]:
class Dog:

    def __init__(self, name):
        self.name = name
        self.tricks = []    # creates a new empty list for each dog

    def add_trick(self, trick):
        self.tricks.append(trick)

In [19]:
d = Dog('Fido')

In [20]:
c = {'1':1,'2':2 }

In [23]:
for i, j in c.items():
    print(i)
    print(j)

1
1
2
2


In [34]:
a = torch.rand([5,5])

In [40]:
a

tensor([[0.3051, 0.8256, 0.9016, 0.3084, 0.4724],
        [0.8549, 0.6731, 0.2568, 0.8787, 0.0829],
        [0.2672, 0.3990, 0.8708, 0.2527, 0.4947],
        [0.0013, 0.6810, 0.1928, 0.7703, 0.8659],
        [0.7745, 0.0075, 0.8590, 0.0879, 0.5092]])

In [29]:
import torch

In [41]:
edge = torch.index_select(a, dim=0, index=torch.tensor([3, 1, 2]))

In [42]:
import torch_scatter
torch_scatter.scatter_mean(edge, dim=0, index=torch.tensor([1, 2, 1]), dim_size=5)

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1343, 0.5400, 0.5318, 0.5115, 0.6803],
        [0.8549, 0.6731, 0.2568, 0.8787, 0.0829],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])

In [45]:
torch.mean(torch.tensor([[0.0013, 0.6810, 0.1928, 0.7703, 0.8659], [0.2672, 0.3990, 0.8708, 0.2527, 0.4947]]), dim=0)

tensor([0.1343, 0.5400, 0.5318, 0.5115, 0.6803])

In [49]:
class Hello: 
    def __init__(self):
        self.h = 0
        

h = Hello()        

In [50]:
def d(h):
    h.h += 1
d(h)

In [51]:
h.h

1

In [60]:
a = np.array([1, 2, 0.0])

In [62]:
a.tolist()

[1.0, 2.0, 0.0]

In [58]:
a.remove(0)

In [59]:
a

[1, 2]